common/models/Lote.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "lote".
 *
 * @property int $id
 * @property int|null $planta_id
 * @property string|null $fecha
 * @property string|null $cuit
 * @property int|null $numero_lote
 * @property string|null $tipo
 * @property int|null $fardos
 * @property float|null $kilos
 * @property float|null $rendimiento
 * @property string|null $calidad
 * @property float|null $lon_1
 * @property float|null $lon_2
 * @property float|null $mic_1
 * @property float|null $mic_2
 * @property int|null $carga_id
 */
class Lote extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'lote';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['planta_id', 'numero_lote', 'fardos', 'carga_id'], 'integer'],
            [['turno'], 'string', 'max' => 1],
            [['fecha'], 'safe'],
            [['kilos', 'rendimiento', 'lon_1', 'lon_2', 'mic_1', 'mic_2'], 'number'],
            [['cuit'], 'string', 'max' => 13],
            [['tipo'], 'string', 'max' => 2],
            [['calidad'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'planta_id' => 'Planta ID',
            'fecha' => 'Fecha',
            'cuit' => 'Cuit',
            'numero_lote' => 'Numero Lote',
            'tipo' => 'Tipo',
            'fardos' => 'Fardos',
            'kilos' => 'Kilos',
            'rendimiento' => 'Rendimiento',
            'calidad' => 'Calidad',
            'lon_1' => 'Lon 1',
            'lon_2' => 'Lon 2',
            'mic_1' => 'Mic 1',
            'mic_2' => 'Mic 2',
            'carga_id' => 'Carga ID',
        ];
    }

    public function getPlanta() {
        return $this->hasOne(Planta::className(), ['id' => 'planta_id']);
    }

    public function getCliente() {
        return $this->hasOne(User::className(), ['cuit' => 'cuit']);
    }
}

frontend/models/Lote.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "lote".
 *
 * @property int $id
 * @property int|null $planta_id
 * @property string|null $fecha
 * @property string|null $cuit
 * @property int|null $numero_lote
 * @property string|null $tipo
 * @property int|null $fardos
 * @property float|null $kilos
 * @property float|null $rendimiento
 * @property string|null $calidad
 * @property float|null $lon_1
 * @property float|null $lon_2
 * @property float|null $mic_1
 * @property float|null $mic_2
 * @property int|null $carga_id
 */
class Lote extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'lote';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['planta_id', 'numero_lote', 'fardos', 'carga_id'], 'integer'],
            [['fecha'], 'safe'],
            [['kilos', 'rendimiento', 'lon_1', 'lon_2', 'mic_1', 'mic_2'], 'number'],
            [['cuit'], 'string', 'max' => 13],
            [['tipo'], 'string', 'max' => 2],
            [['calidad'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'planta_id' => 'Planta ID',
            'fecha' => 'Fecha',
            'cuit' => 'Cuit',
            'numero_lote' => 'Numero Lote',
            'tipo' => 'Tipo',
            'fardos' => 'Fardos',
            'kilos' => 'Kilos',
            'rendimiento' => 'Rendimiento',
            'calidad' => 'Calidad',
            'lon_1' => 'Lon 1',
            'lon_2' => 'Lon 2',
            'mic_1' => 'Mic 1',
            'mic_2' => 'Mic 2',
            'carga_id' => 'Carga ID',
        ];
    }
}

frontend/controllers/LoteController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\LoteSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

/**
 * LoteController implements the CRUD actions for Lote model.
 */
class LoteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lote models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoteSearch();      
        $dataProvider = $searchModel->search(Yii::$app->request->get());   
       
        
        return $this->render('index', [
            
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Lote model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Lote model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lote();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Lote model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Lote model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Lote model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lote the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = LoteSearch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Despliega en pdf un Resumen del Cliente.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
     public function actionDocumento($id)
     {
        $model = $this->findModel($id);
        
        // get your HTML raw content without any layouts or scripts
        $content = $this->renderPartial('documento',['model'=>$model]);
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            // your html content input
            'content' => $content,  
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
                // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
                // call mPDF methods on the fly
            'methods' => [ 
                //'SetHeader'=>['Krajee Report Header'], 
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render(); 
       
     }
}

frontend/views/lote/_form.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\web\UploadedFile;
use common\models\Planta;
use common\models\Carga;
use kartik\datetime\DateTimePicker;

?>
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
        <div class="row">           
            <div class="col-xs-12 col-sm-3">
                <?= $form->field($model, 'planta_id')->dropDownList(['' => 'Ninguno'] + Carga::PLANTAS); ?>
            </div>
                       
            <div class="col-xs-12 col-sm-3">
                    <?= $form->field($model, 'turno')->dropDownList(['' => 'Ninguna'] + Carga::TURNOS); ?>
            </div>
        
            <div class="col-xs-12 col-sm-3">                 
                    <?= $form->field($model, 'fecha')->widget(DateTimePicker::classname(),[
                            'name' => 'fecha',
                            'convertFormat'=> true,
                            'options' => [
                                'placeholder' => 'Fecha ...',
                                'label' => 'Fecha de Carga',
                            ],
                            'convertFormat' => true,
                            'pluginOptions' => [
                                'format' => 'dd/MM/yyyy hh:mm',
                                'autoclose'=>true,
                                'todayHighlight' => true
                            ]
                        ]);
                    ?>           
                </div>
                </br>

            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <div class="form-group">
                    <?= $form->field($model, 'imageFile')->fileInput() ?>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3">
                <div class="form-group">
                    <?= Html::submitButton('Cargar Datos', ['class' => 'btn btn-info']) ?>
                </div>
            </div>        
        </div>
<?php ActiveForm::end() ?>

frontend/views/lote/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Lote */

$this->title = 'Create Lote';
$this->params['breadcrumbs'][] = ['label' => 'Lotes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/lote/documento.php
<?php

/** @var Resumen $model */

use common\models\Lote;
use common\models\Planta;
use common\models\User;
use yii\helpers\Html;
?>
<div >  
    
    <table style="border:1px solid black;margin-left:150px;width:400px">
        <tr>
            <td style="padding-left:140px;" colspan="2"><?php echo 
            Html::img('@web/imagen/logosafico.jpg', ['alt'=>'Safico', 
            'width'=>'150px']);?>
            </td>
            <td></td>
        </tr>   
        <tr>
            <td style="width:150px"><b>Numero de Entrega:<b></td>
            <td><?php echo $model->id;?></td>
        </tr>
        <tr>
            <td><b>Cliente:<b></td>
            <td><?php 
                    $resultado= User::find('nombre')->where(['cuit' => intval(Yii::$app->user->identity->username)])->one();
                    echo utf8_encode($resultado['nombre']);
            ?></td>
        </tr>
        <tr>
            <td><b>Fecha:<b></td>
            <td><?php echo date('d/m/Y',strtotime($model->fecha))?></td>
        </tr>
        <tr>
            <td><b>Planta:<b></td>
            <td><?php echo ($model->planta_id) ? utf8_encode(Planta::findOne($model->planta)->nombre):''?></td>
        </tr>
        <tr>
            <td><b>Numero de Lote:<b></td>
            <td><?php echo ($model->numero_lote) ? $model->numero_lote : ''?></td>
        </tr>
        <tr>
            <td><b>Fardos:<b></td>
            <td><?php echo ($model->fardos) ? $model->fardos : ''?></td>
        </tr>
        <tr>
            <td><b>Kilos:<b></td>
            <td><?php echo ($model->kilos) ? $model->kilos : ''?></td>
        </tr>
        <tr>
            <td><b>Calidad:<b></td>
            <td><?php echo ($model->calidad) ? $model->calidad : ''?></td>
        </tr>
        <tr>
            <td><b>Lon 1:<b></td>
            <td><?php echo ($model->lon_1) ? $model->lon_1 : ''?></td>
        </tr>
        <tr>
            <td><b>Lon 2:<b></td>
            <td><?php echo ($model->lon_2) ? $model->lon_2 : ''?></td>
        </tr>
        <tr>
            <td><b>Mic 1:<b></td>
            <td><?php echo ($model->mic_1) ? $model->mic_1 : ''?></td>
        </tr>
        <tr>
            <td><b>Mic 2:<b></td>
            <td><?php echo ($model->mic_2) ? $model->mic_2 : ''?></td>
        </tr>
        
    </table>
</div>

frontend/views/lote/index.php
<?php

use common\models\Planta;
use common\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lotes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php $nombre = User::find('nombre')->where(['username' => intval(Yii::$app->user->identity->username)])->one();   ?>
    <?= 'CUIT: ' . Yii::$app->user->identity->cuit  ?>
    <?= 'Nombre: ' . $nombre->nombre?> 
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,       
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            ['attribute'=>'planta',
            'value'=>function($data){
                //var_dump($data->planta); die();
                //return $data->planta ? utf8_encode($data->planta->nombre) : "";
                return $data->planta ? Planta::findOne($data->planta)->nombre : "";
            }
            ],
            [
                'label'=>'Fecha',
                'attribute'=>'fecha',
                'value'=>function($data){
                    return date('d/m/Y ',strtotime($data->fecha));
                },
            ],
            //'cuit',
            'numero_lote',
            //'tipo',
            //'fardos',
            //'kilos',
            //'rendimiento',
            //'calidad',
            //'lon_1',
            //'lon_2',
            //'mic_1',
            //'mic_2',
            //'carga_id',

            [
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['style' => 'max-width: 200px'],
                'template' => '{documento} ',
                'buttons' => [
                    
                    'documento' => function ($url, $model) {
                        

                            $url = \yii\helpers\Url::toRoute(['lote/documento', 'id' => $model->id]);
                            
                            return Html::a('<span class="glyphicon glyphicon-print"></span>', $url, [
                                'title' => Yii::t('yii', 'Imprimir Lote'), 'class' => 'imprimir',
                                'data-id' => $model->id , 'target' => '_blank'
                            ]);
                        
                    },
                    
                ],
            ]
        ],
    ]); ?>


</div>

frontend/views/lote/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Lote */

$this->title = 'Update Lote: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Lotes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="lote-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/lote/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Lote */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Lotes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="lote-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'planta_id',
            'fecha',
            'cuit',
            'numero_lote',
            'tipo',
            'fardos',
            'kilos',
            'rendimiento',
            'calidad',
            'lon_1',
            'lon_2',
            'mic_1',
            'mic_2',
            'carga_id',
        ],
    ]) ?>

</div>